rsync -av wa@10.1.90.130:/home/ap/was/AppServer/profiles/AppSrv01/installedApps  /home/svnbak/docker/wasapps 
rsync -av wa@10.1.90.131:/home/ap/was/AppServer/profiles/AppSrv01/installedApps  /home/svnbak/docker/wasapps   
rsync -av wa@10.1.94.14:/home/ap/was/AppServer/profiles/AppSrv01/installedApps   /home/svnbak/docker/wasapps  
rsync -av wa@10.1.115.3:/home/ap/was/AppServer/profiles/AppSrv01/installedApps   /home/svnbak/docker/wasapps  
rsync -av wa@10.1.115.4:/home/ap/was/AppServer/profiles/AppSrv01/installedApps   /home/svnbak/docker/wasapps  
rsync -av wa@10.1.94.22:/home/ap/was/AppServer/profiles/AppSrv01/installedApps   /home/svnbak/docker/wasapps  
rsync -av wa@10.1.115.6:/home/ap/was/AppServer/profiles/AppSrv01/installedApps   /home/svnbak/docker/wasapps  
rsync -av wa@10.1.115.9:/home/ap/was/AppServer/profiles/AppSrv01/installedApps   /home/svnbak/docker/wasapps  
rsync -av wa@10.1.94.14:/home/ap/was/AppServer/profiles/AppSrv02/installedApps   /home/svnbak/docker/wasapps  
rsync -av wa@10.1.115.3:/home/ap/was/AppServer/profiles/AppSrv02/installedApps   /home/svnbak/docker/wasapps  
rsync -av wa@10.1.115.4:/home/ap/was/AppServer/profiles/AppSrv02/installedApps   /home/svnbak/docker/wasapps  
rsync -av wa@10.1.94.22:/home/ap/was/AppServer/profiles/AppSrv02/installedApps   /home/svnbak/docker/wasapps  
rsync -av wa@10.1.115.6:/home/ap/was/AppServer/profiles/AppSrv02/installedApps   /home/svnbak/docker/wasapps  
rsync -av wa@10.1.115.9:/home/ap/was/AppServer/profiles/AppSrv02/installedApps   /home/svnbak/docker/wasapps  
